= Python

== Настройка

1. Вы собираетесь обучаться программированию и узнаете как сделать игру на языке Python.
+
[NOTE]
.Знали ли вы?
====
Такие веб-сайты как YouTube и Instagram написаны на Python.
====
+
Перед тем как начать писать код, вам нужно будет подготовить свой компьютер к написанию программ на Python. Для этого
вам потребуется установить на компьютер Python и текстовый редактор, а также знание о том, как запускать программы
Python.

2. Для того, чтобы установить Python, перейдите по ссылке http://dojo.soy/py-setup и нажмите на кнопку
  _Download Python 3_. После _3_ могут быть ещё и другие цифры, но они меняются слишком часто, чтобы их указывать. Не
  переживайте о них.
+
Когда установщик скачается, запустите его и выберите все настройки по умолчанию.

3. Теперь, вам нужен текстовый редактор, в котором вы будете работать с Python. Мы рекомендуем Atom, который вы можете
скачать с http://atom.io , но вы можете пользоваться другим редактором, если вы с ним более знакомы, или он просто вам
более по душе.

4. Как только вы настроите Python и текстовый редактор, вы будете готовы к написанию программ. Осталось только
  убедиться, что мы всё настроили правильно и что мы знаем, как запускать программу Python. Для этого проделаем
  следующие шаги:

- Создайте новую папку для ваших проектов, «Суши-Карточек» , написанных на Python

- Откройте ваш текстовый редактор и создайте новый файл. Сохраните его в папку и назовите его _beginner_sushi.py_

- Откройте командную строку вашего компьютера (_командная строка_ для Windows и _терминал_ для Mac) и откройте свою
  папку, используя команду _cd_

- Когда вы откроете папку в командной строке, вы сможете запустить пустой файл с помощью этой команды, введённой в
  командную строку:
+
[source,bash]
----
python3 beginner_sushi.py
----
+
Если всё сработало правильно, то вы не должны увидеть никаких сообщений, когда будете запускать эту программу.
+
[NOTE]
.Запуск программы
====
В последующих карточках от вас будет требоваться запуск программы

Это означает проделать именно то, что мы только что сделали: применить к папке с нашим файлом команду python3 и имя
программы, чтобы программа выполнила свою функцию!
====

== Ваша первая программа на Python

1. Настало время для начала работы с Python. Сейчас вы сделаете так, что компьютер поздоровается со всеми. Для этого
в наш файл нужно написать:
+
[source,python]
----
print("Hello everyone")
----
+
Запустите этот код и посмотрите на результат!
+
Попробуйте менять содержимое кавычек `"`, возможно, добавив своё имя, и запустите программу снова.

2. Теперь, добавьте другую строку: Ваш код должен выглядеть примерно  так:
+
[source,python]
----
print("Hello everyone")
print("The Code, It’s calling to you, Just let it in.")
----
+
Запустите снова.
+
Вы заметили как текст (называемый строкой) из второй функции print находится ниже? Это происходит потому, что когда
компьютер получает команду `print` происходит следующее:

- Происходит считывание кода в скобках и определяется, что там находится

- Как только содержимое скобок определено, оно печатается на экран

- В конце строки ставится «переход на новую строку» по умолчанию

3. Почему компьютеру нужно определять содержимое скобок? Потому что компьютер может составить строку из частей, которые
   вы ему подаёте.
+
Попробуйте! Используйте этот код, но замените `"my name"` на ваше имя (Но не забудьте оставить кавычки `"`!):
+
[source,python]
----
name = "my name"
print("Hello "+name)
print("The Code, it’s calling to you. Just let it in")
----
+
[NOTE]
.Пробел после «Hello»
====
Вам необходимо добавить пробел перед переменной или вы получите «Hellomy name"! Python Не лингвист и просто выполняет
ваши указания!
====

4. Вы только что создали переменную, обозначенную `name`. Её можно представить как коробку с ярлыком внутри компьютера.
   В эту коробку вы можете положить всё, что вы захотите. Затем, вы можете по этому ярлыку с помощью Python найти эту
   коробку и использовать её содержимое в своём коде. Иными словами, вы создали переменную `name` и сохранили `"[my name]"`
   в ней. На следующей строке вы использовали эту переменную чтобы добавить это имя к своему приветствию, используя
   символ `+` чтобы добавить эту переменную к концу строки.

== Общение с пользователем

1. Сделать так, чтобы ваше имя было в конце сообщения `"Hello "`, конечно, здорово, но почему бы просто не написать
  `"Hello [my name]"`? Потому что с переменной вам не нужно заранее знать подобное при написании программы. Вы даже
  можете спросить у пользователя, что он хочет, чтобы было выведено. Приведите свой код в следующий вид:
+
[source,python]
----
name = input("What is your name?")
print("Hello "+name) 
print("The Code, it's calling to you. Just let it in.")
----
+
Попробуйте запустить эту программу. После ввода имени вам потребуется нажать `"Enter"`.

2. Теперь, давайте попросим пользователя ввести число. Обратите внимание, что `+` может использоваться по обе стороны от
   переменной. Запустите программу, ответьте на вопросы и посмотрите, что же получится в итоге.
+
[source,python]
----
name = input("What is your name?")
my_number = input("Hello "+name+", please pick a number")
print("Your number is "+my_number)
----
3. А что если вы хотите добавить число к своей переменной? Добавьте строку которая добавит переменную `my_number`.
+
[source,python]
----
name = input("What is your name?")
my_number = input("Hello "+name+" please pick a number")
my_number = int(my_number) + 1
print("Your number is "+str(my_number))
----
+
[NOTE]
====
Обратите внимание, вы взяли значение из переменной, поменяли его и положили в ту же переменную, и всё в одной строке!
====
+
Вы могли заметить функции `int()` и `str()` рядом с `my_number`, но для чего же они?
+
Это для того, чтобы Python мог различать какую `«1»` мы хотим использовать, так как для Python есть две разные
`«единицы»`: одна для математических вычислений, а другая, которую он использует в предложениях. Когда вы ставите
`int()` рядом с переменной Python распознает её как _целое число (integer)_, а когда вы ставите `str()` то Python
распознает её как _текстовую строку (string)_.
+
Целые числа и строки это типы переменных, которые работают с определёнными функциями (как `+` и `print`) только если
переданные им переменные правильного типа.
+
[NOTE]
.Математика
====
Вы уже познакомились с суммированием, но также вы можете:

- Вычитать с помощью `–`
- Умножать с помощью `*`
- Делить с помощью `/`
====

== Сравнения и условия (Использование if)

1. Python может сравнивать значения двух чисел. Это может нам пригодиться (например, достаточно ли у игрока денег на покупку этих брюк?). Это можно сделать с помощью особых символов:

- `a > b` проверяет, больше ли `a`, чем `b`
- `a < b` проверяет, меньше ли `a`, чем `b`
- `a == b` проверяет, равны ли значения `a` и `b`
- `a != b` проверяет, не равны ли значения `a` и `b`
- `a >= b` проверяет, `a` больше или равно `b`
- `a <= b` проверяет, `a` меньше или равно `b`
+
[NOTE]
.==
====
Два символа равно используются для сравнения переменных, потому что единичный такой символ используется для присвоения
значений переменным
====

2. Вы можете использовать эти сравнения внутри условий `if`: часть кода, которая будет выполняться, если условие
(в скобках) истинно. В этом случае, это печать текста.
+
[source,python]
----
if(my_number > 100):
  print("That's a big number!")
----
+
[NOTE]
.Отступы
====
Перед print мы сделали отступ. Это означает, что перед ним находится четыре пробела. Python необходимы эти пробелы для
правильного считывания программы.
====

3. А теперь, давайте объединим эту часть кода с программой из предыдущей карточки. Приведите свою программу к следующему виду:
+
[source,python]
....
name = input("What is your name?")
my_number = input("Hello "+name+" please pick a number")
my_number = int(my_number)
print("Your number is "+str(my_number))

if(my_number > 100):
  print("That's a big number!")
....
+
Запустите программу и попробуйте вводить разные числа, больше и меньше 100. Что произойдёт, если вы введёте ровно 100?

4. Вы можете также объединять условия, используя and и or. Это позволит вам составлять такие программы:
+
[source,python]
....
if(my_number >= 20 and my_number < 30):
  print("That number is in the twenties!")
....
+
Или, например:
+
[source,python]
....
if(food == "Cake" or food == "Chocolate" or food == "Pie"):
  print("Sounds tasty!")
....

== Продвинутое использование условий (if, else, elif)

1. Но что если мы хотим проверить, что число, введённое пользователем, достаточно большое и уведомить его, если он
   далеко? Например, если введено больше 100. Тогда, нам нужно сообщить пользователю о том, что введённый им номер
   достаточно большой или сообщить ему, где он ошибся. Попробуйте это:
+
[source,python]
....
name = input("What is your name?")
my_number = input("Hello "+name+" please pick a number that's bigger than 100")
my_number = int(my_number)
print("Your number is "+str(my_number))

if(my_number > 100):
  print("That's a big number!")
else: 
  print("That number is too small!")
....
+
В данном случае, else выполняет функцию if, но её часть когда выполняется, если условие в if неверно.

2. Быть может, нам стоит сообщить пользователю, что они близки? Например, если введённое число больше `90`? Тогда можно
   использовать `elif`. Это `else` и `if` вместе, то есть, эта часть кода выполняется, если условие в скобках `if`
   ложно, а в скобках `elif` истинно. Таким образом, нужно добавить этот код, чтобы пользователь знал, когда он почти
   угадал:
+
[source,python]
....
elif(my_number > 90):
  print("Almost there!")
....
+
И вот как это условие должно стоять в основной программе. Обратите внимание, `elif` должен стоять между `if` и `else`.
+
[source,python]
....
name = input("What is your name?")
my_number = input("Hello "+name+" please pick a number that's bigger than 100")
my_number = int(my_number)
print("Your number is "+str(my_number))

if(my_number > 100):
  print("That's a big number!")
elif(my_number > 90):
  print("Almost there!")
else:
  print("That number is too small!")
....

== Циклы

1. Теперь вы можете попросить пользователя ввести число, проверить, нужной ли оно величины и сообщить, если нет. Но что
   если мы хотели бы продолжать обращаться к пользователю, пока не получили бы правильный ответ? Можно было бы
   использовать `if` в `if`, но как же нам поступить если мы не знаем, сколько пользователю потребуется попыток?
+
Нам нужен способ задавать вопрос снова и снова, до тех пор, пока мы не получим нужный ответ. В компьютерном
программировании это осуществляется с помощью циклов. В нашем случае мы будем использовать цикл `while`.

2. Цикл while чем-то похож на `if`: у него есть часть кода, выполняющаяся только если условие в скобках истинна.
   Отличие в том, что цикл `while` будет постоянно выполнять свою часть кода, пока условие не станет ложным. Не
   забудьте, что цикл `while` должен завершаться, или он будет выполняться вечно! На деле цикл выглядит так:
+
[source,python]
....
while(my_number < 100):
  my_number = input("Hello "+name+" please pick a number that's bigger than 100")
my_number = int(my_number)
....

3. Теперь, давайте добавим цикл `while` к нашей программе.
+
[source,python]
....
name = input("What is your name?")
my_number = 0
# Loop as long as "my_number" is less than 100
while(my_number < 100):
  # Ask the user for a number
  my_number = input("Hello "+name+" please pick a number that's bigger than 100")
  # Convert the user's answer from a string to an integer
  my_number = int(my_number)
  print("Your number is "+str(my_number))
  # Check if the number is bigger than 100
  if(my_number > 100):
    print("That's a big number!")
  elif(my_number > 90):
    print("Almost there! Try again!")
  else:
    print("That number is too small! Please try again!")
    # If my_number is smaller than 100 at this point, loop again
....
+
[NOTE]
.Комментарии
====
Это заметки для других программистов (или для вас), которые игнорируются при запуске программы. В Python они начинаются с # и длятся до конца строки
====

== Давайте сделаем игру!

1. Теперь вы знаете о:

- операторе `print`: Общение с пользователем
- переменных: Возможность программы запоминать и преобразовывать значения
- строках: Текстовых частях программ
- `input`: Способ получения данных от пользователя
- математике: Как выполнять математические вычисления с числами
- целых числах: Числа, с которыми выполняются математические вычисления
- условиях `if`: Выполнение части программы при истинности высказывания
- циклах `while`: Постоянное выполнение части кода, пока условие не станет ложным

2. Попробуйте с помощью этих идей сделать игру:

- Есть целое число (integer), между 1 и 9, которое программа тайно выбирает
- У игрока 5 попыток отгадать это число
- Игра объясняет правила игроку
- После каждой догадки, игра говорит игроку, меньше или больше его число загаданного, и угадал ли он, а также сообщает о количестве оставшихся попыток
- Если игрок побеждает, то он получает сообщение о победе
- Если игрок не угадывает число за 5 раз, то игра заканчивается и выводится соответствующее сообщение

3. Вы можете взглянуть на пример игры здесь: http://dojo.soy/py-dice.

4. Вам не хватает лишь одной детали, чтобы сделать эту игру: Способа получить наугад число от 1 до 9. Код для этого ещё
вам неизвестен, поэтому просто воспользуйтесь этими магическими словами. Они будут объяснены в более поздних
Суши-Карточках. Поставьте это в качестве первой строки вашей программы:
+
[source,python]
....
from random import randint as dice
....
+
Теперь, где бы вам не потребовалось взять случайное число от 1 до 9, просто используйте `dice(1,9)`. Например:
+
[source,python]
....
secret_number = dice(1,9)
....


5. Теперь попробуйте сделать игру! Не забудьте использовать предыдущие карточки. Если у вас возникли проблемы или когда
   вы завершите, вы можете взглянуть на мой вариант на http://dojo.soy/py-guess. Не волнуйтесь, если ваш вариант
   выглядит по-другому, главное – чтобы он работал. Удачи!
+
[NOTE]
.Что скажете?
====
Вы прошли этот набор Суши-Карточек. Мне хотелось бы услышать ваше мнение о них. Если вас не затруднит, то пожалуйста
напишите отзыв здесь: http://dojo.soy/py-beginner
====
